import bs.ModLoader
import bs.SemverUtils
import groovy.json.JsonOutput
import groovy.json.JsonSlurper
import org.embeddedt.embeddium.gradle.DiscordNotifier

import java.nio.file.Files
import java.nio.file.StandardCopyOption
import static bs.ModLoader.FABRIC
import static bs.ModLoader.FORGE
import static bs.ModLoader.NEOFORGE

plugins {
    id 'java'
    id 'embeddium-fabric-remapper' apply false
}

group = rootProject.properties.mod_package
version = rootProject.properties.mod_version
ModLoader loader = ModLoader.fromProject(project)
archivesBaseName = "${rootProject.properties.mod_id}-$loader.friendlyName-mc${ModLoader.getMinecraftVersion(project).replaceAll("^1\\.", "")}"

def packageJar = tasks.create("packageJar", Copy.class) {
    into("${rootProject.layout.buildDirectory.get()}/libs/${E.p["mod_version"]}")
}

project.ext["loom.platform"] = loader.friendlyName
project.ext["cur_mc_ver"] = ModLoader.getMinecraftVersion(project)

repositories {
    mavenCentral()
    // for Mod Menu
    maven {
        url = "https://maven.terraformersmc.com/releases"
    }
    // For NeoForge
    maven {
        url = "https://maven.neoforged.net/releases"
    }
    // For NeoForge PRs
    if (versionedProperty("neoforge_pr") != null) {
        maven {
            url "https://prmaven.neoforged.net/NeoForge/pr${versionedProperty("neoforge_pr")}"
            content {
                includeModule("net.neoforged", "neoforge")
            }
        }
    }
    // For Patchment mappings
    if (rootProject.properties.parchment_version) {
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }
    }
    // For Forge
    maven {
        url = "https://maven.minecraftforge.net/"
    }
}
apply plugin: 'dev.architectury.loom'
apply plugin: 'embeddium-fabric-remapper'

ext.mc_version_prop_suffix = ext.cur_mc_ver.toString().replace('.', '_')

def versionedProperty(String name) {
    return rootProject.properties[name + "_" + ModLoader.getMinecraftVersion(project).replace('.', '_')]
}

stonecutter.const("fabric", loader == FABRIC)
stonecutter.const("forge", loader == FORGE)
stonecutter.const("neoforge", loader == NEOFORGE)
stonecutter.const("forgelike", loader == NEOFORGE || loader == FORGE)
stonecutter.const("ffapi", versionedProperty("ffapi") != null || loader == FABRIC)

loom {
    accessWidenerPath = project.rootDir.toPath().resolve("src/main/resources/${E.p.mod_id}.accesswidener").toFile()
}
// Use vanilla mixin on Forge
if (loader == FORGE) {
    loom {
        forge {
            useCustomMixin = false

            mixinConfig "${E.p.mod_id}.mixins.json"
        }
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:${ModLoader.getMinecraftVersion(project)}"

    mappings loom.layered {
        officialMojangMappings {
            nameSyntheticMembers = true
        }
        if (versionedProperty("parchment_version") != null) {
            parchment("org.parchmentmc.data:parchment-${versionedProperty("parchment_version")}@zip")
        }
    }

    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")

    if (loader == FABRIC) {
        modImplementation "net.fabricmc:fabric-loader:$rootProject.properties.fabricloader"
        modCompileOnly "com.terraformersmc:modmenu:$project.properties.modmenu", {
            transitive = false
        }
        if (rootProject.properties.fabric_api_modules == "*") {
            if (rootProject.properties.include_fabric_api_modules == "true") {
                throw new RuntimeException("You can't include the entirety of Fabric API!")
            }
            modApi "net.fabricmc.fabric-api:fabric-api:${versionedProperty("fabric_api_version")}"
        } else {
            for (String module in rootProject.properties.fabric_api_modules.split(",") as String[]) {
                var dep = fabricApi.module(module, versionedProperty("fabric_api_version"))
                modApi dep
                if (rootProject.properties.include_fabric_api_modules == "true") {
                    include(dep)
                }
            }
        }
    } else {
        // Forge-like

        if (loader == FORGE) {
            forge "net.minecraftforge:forge:${versionedProperty("forge")}"

            if (rootProject.properties.mixinextras) {
                implementation(include("io.github.llamalad7:mixinextras-$loader.friendlyName:$rootProject.properties.mixinextras"))
                compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:$rootProject.properties.mixinextras"))
                //forgeRuntimeLibrary "io.github.llamalad7:mixinextras-$loader.friendlyName:$rootProject.properties.mixinextras"
            }
        } else if (loader == NEOFORGE) {
            neoForge "net.neoforged:neoforge:${versionedProperty("neoforge")}"
        }

        compileOnly "net.fabricmc:fabric-loader:$rootProject.properties.fabricloader"
    }
}

jar {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_${archivesBaseName}"}
    }
}

processResources {
    def dep = versionedProperty("minecraft_dependency")
    if (loader == FORGE || loader == NEOFORGE) {
        dep = SemverUtils.convertSemverPredicateToMavenPredicate(dep)
    }

    inputs.property "forgeid", loader == NEOFORGE ? "neoforge" : "forge"
    inputs.property "minecraft_dependency", dep
    inputs.property "mod_version", version
    inputs.property "mod_id", rootProject.properties.mod_id
    inputs.property "mod_display_name", rootProject.properties.mod_display_name
    inputs.property "mod_description", rootProject.properties.mod_description
    inputs.property "homepage_url", rootProject.properties.homepage_url
    inputs.property "sources_url", rootProject.properties.sources_url
    inputs.property "issue_tracker_url", rootProject.properties.issue_tracker_url
    inputs.property "license", rootProject.properties.license
    inputs.property "fabricloader", rootProject.properties.fabricloader
    inputs.property "contributors", rootProject.properties.mod_contributors.toString()
    inputs.property "authors", rootProject.properties.mod_authors.toString()
    inputs.property "fabric_api_modules", rootProject.properties.fabric_api_modules

    filesMatching(["fabric.mod.json", "META-INF/mods.toml", "quilt.mod.json"]) {
        def map = [
                "forgeid": loader == NEOFORGE ? "neoforge" : "forge",
                "minecraft": dep,
                "mod_version": version,
                "mod_id": rootProject.properties.mod_id,
                "mod_display_name": rootProject.properties.mod_display_name,
                "mod_description": rootProject.properties.mod_description,
                "homepage_url": rootProject.properties.homepage_url,
                "sources_url": rootProject.properties.sources_url,
                "issue_tracker_url": rootProject.properties.issue_tracker_url,
                "license": rootProject.properties.license,
                "fabricloader": rootProject.properties.fabricloader,
                "contributors": rootProject.properties.mod_contributors.toString().split(","),
                "authors": rootProject.properties.mod_authors.toString().split(",")
        ]
        expand map
    }
    doLast {
        if (loader == NEOFORGE) {
            fileTree(dir: outputs.files.asPath, include: "META-INF/mods.toml").each { File file ->
                file.text += "\n\n[[mixins]]\nconfig = \"${rootProject.properties.mod_id}.mixins.json\""
            }
            fileTree(dir: outputs.files.asPath, include: "META-INF/mods.toml").each { File file ->
                Files.copy(file.toPath(), java.nio.file.Path.of(outputs.files.asPath).resolve("META-INF/neoforge.mods.toml"), StandardCopyOption.REPLACE_EXISTING)
                file.delete()
            }
        }
        if (loader == FABRIC) {
            fileTree(dir: outputs.files.asPath, include: "fabric.mod.json").each { File file ->
                def parse = new JsonSlurper().parse(file)
                def fModulesString = rootProject.properties.fabric_api_modules
                if (fModulesString == "*") {
                    parse.depends["fabric-api"] = ">=" + versionedProperty("fabric_api_version")
                } else {
                    def fModules = fModulesString.split(",")
                    for (String s in fModules) {
                        // ^ means until the next major
                        parse.depends[s] = "^" + fabricApi.module(s, versionedProperty("fabric_api_version")).getVersion()
                    }
                }
                file.text = JsonOutput.prettyPrint(JsonOutput.toJson(parse))
            }
        }
    }

    if (loader == FORGE || loader == NEOFORGE) {
        exclude 'fabric.mod.json'
    } else if (loader == FABRIC) {
        exclude 'META-INF/mods.toml', 'META-INF/accesstransformer.cfg', 'pack.mcmeta'
    }
}

remapJar {
    if (loader == FORGE || loader == NEOFORGE) {
        atAccessWideners.add("${rootProject.properties.mod_id}.accesswidener")
    }
}

if (loader == FORGE) {
    configurations.all {
        resolutionStrategy {
            force 'net.sf.jopt-simple:jopt-simple:5.0.4'
        }
    }
}

if (stonecutter.current.isActive) {
    tasks.register("runActive") {
        group = "project"
        dependsOn("runClient")
    }
    tasks.register("packageActive") {
        group = "project"
        dependsOn("packageJar")
    }
    tasks.register("publishPackagesToDiscord") {
        outputs.upToDateWhen { false }
        doLast {
            DiscordNotifier.publishEmbeddiumJar(project)
        }
    }
}

tasks.named("validateAccessWidener") {
  enabled = false
}

afterEvaluate {
    packageJar.dependsOn(remapJar)
    packageJar.from(remapJar.archiveFile)
    build.finalizedBy(packageJar)
}
