org.gradle.jvmargs=-Xmx5G
# Gradle stuff
architectury_loom_version=1.7-SNAPSHOT
stonecutter_version=0.4.2

mod_version=2.0.0
mod_package=org.embeddedt.embeddium
mod_id=embeddium
mod_display_name=Embeddium
mod_description=An open-source client performance mod for Minecraft
# Comma separated, i.e.: "Person A,Person B,Person C"
mod_authors=embeddedt
mod_contributors=jellysquid3
license=LGPL-3.0

homepage_url=https://github.com/Jab125/multiloader-example-mod
sources_url=https://github.com/Jab125/multiloader-example-mod
issue_tracker_url=https://github.com/Jab125/multiloader-example-mod/issues

# Supports Forge, Fabric, and NeoForge. There is no need to support Quilt since all Fabric mods support Quilt, just don't access the impl classes.
# Unlike the preprocessor version, Fabric can be safely removed here. Make sure to switch your active project first!
enabled_platforms=forge,fabric

minecraft_dependency_1_20_1=1.20.1
minecraft_dependency_1_20_2=1.20.2

parchment_version_1_20_1=1.20.1:2023.09.03
# If this is blank, the stock version is used. This also bundles mixinextras into the JAR file if it is not the same as the stock version.
mixinextras=0.3.5

# Fabric Stuff
fabricloader=0.15.11
modmenu=11.0.1
fabric_api_version_1_20_1=0.91.0+1.20.1
fabric_api_version_1_20_2=0.91.6+1.20.2
fabric_api_version_1_21_1=0.100.7+1.21
fabric_api_modules=fabric-api-base,fabric-resource-loader-v0,fabric-rendering-fluids-v1,fabric-renderer-api-v1,fabric-rendering-data-attachment-v1,fabric-renderer-indigo
include_fabric_api_modules=false
# Example below
#fabric_api_modules=fabric-api-base,fabric-resource-loader-v0
#include_fabric_api_modules=true

# NeoForge stuff
neoforge=21.0.140-beta
neoforge_pr=

# Forge Stuff
forge_1_20_1=1.20.1-47.3.0