import org.embeddedt.embeddium.gradle.build.conventions.CeleritasBuildConstants
import org.embeddedt.embeddium.gradle.build.conventions.LWJGLHelper
import org.embeddedt.embeddium.gradle.build.conventions.ProductionJarHelper

plugins {
    id "celeritas.platform-conventions"
    id "celeritas.unimined-platform-conventions"
}

group = "org.embeddedt"
version = rootProject.version

archivesBaseName = "celeritas-forge-1.12.2"

configurations {
    modCompileOnly
    compileOnly.extendsFrom modCompileOnly
}

unimined.minecraft {
    combineWith(project(":common"), project(":common").sourceSets.getByName("main"))

    version "1.12.2"

    mappings {
        searge()
        mcp("stable", "39-1.12")
    }

    minecraftForge {
        loader "14.23.5.2860"
        mixinConfig "mixins.celeritas.json"
        accessTransformer(file("src/main/resources/META-INF/celeritas_at.cfg"))
    }

    runs.config("client") {
        javaVersion = JavaVersion.VERSION_21
        mainClass = "com.gtnewhorizons.retrofuturabootstrap.Main"
        jvmArgs += CeleritasBuildConstants.RFB_JVM_ARGS
        systemProperty("fml.coreMods.load", "zone.rong.mixinbooter.MixinBooterPlugin,me.eigenraven.lwjgl3ify.core.Lwjgl3ifyCoremod,org.taumc.celeritas.core.CeleritasLoadingPlugin")
    }

    runs.config('server') {
        enabled = false
    }

    mods {
        remap(configurations.modCompileOnly) {
        }
    }
}

dependencies {
    shadow("org.joml:joml:1.10.5")
    implementation("org.joml:joml:1.10.5")
    implementation("zone.rong:mixinbooter:10.5")
    implementation("io.github.twilightflower:lwjgl3ify:1.0.1") {
        exclude group: 'mezz.jei'
        exclude group: 'curse.maven'
    }
    implementation("io.github.twilightflower:lwjgl3ify:1.0.1:forgePatches") {
        exclude group: 'mezz.jei'
        exclude group: 'curse.maven'
    }
    implementation("com.gtnewhorizons.retrofuturabootstrap:RetroFuturaBootstrap:1.0.7") {
        exclude group: 'org.apache.logging.log4j'
    }

    modCompileOnly("maven.modrinth:fluidlogged-api:3.0.6")
}

LWJGLHelper.addLwjgl3(project)

ProductionJarHelper.configureProcessedResources(project)
ProductionJarHelper.setupLegacyFMLManifest(project)
ProductionJarHelper.createShadowRemapJar(project)

