import org.embeddedt.embeddium.gradle.build.conventions.LWJGLHelper
import org.embeddedt.embeddium.gradle.build.conventions.ProductionJarHelper
import xyz.wagyourtail.jvmdg.gradle.task.files.DowngradeFiles

plugins {
    id "celeritas.platform-conventions"
    id "celeritas.unimined-platform-conventions"
    id "xyz.wagyourtail.jvmdowngrader" version "1.1.3"
}

group = "org.embeddedt"
version = rootProject.version

archivesBaseName = "celeritas-forge-1.12.2"

configurations {
    modCompileOnly
    compileOnly.extendsFrom modCompileOnly
}

unimined.minecraft {
    combineWith(project(":common"), project(":common").sourceSets.getByName("main"))

    version "1.12.2"

    mappings {
        searge()
        mcp("stable", "39-1.12")
    }

    minecraftForge {
        loader "14.23.5.2860"
        mixinConfig "mixins.celeritas.json"
        accessTransformer(file("src/main/resources/META-INF/celeritas_at.cfg"))
    }

    def downgradeClient = tasks.register("downgradeClient", DowngradeFiles) {
        inputCollection = sourceSet.output.classesDirs + sourceSet.runtimeClasspath
        classpath = project.files()
        outputCollection.files
    }

    runs.config("client") {
        javaVersion = JavaVersion.VERSION_1_8
        classpath = downgradeClient.get().outputCollection + files(jvmdg.getDowngradedApi(JavaVersion.VERSION_1_8))
        systemProperty("fml.coreMods.load", "zone.rong.mixinbooter.MixinBooterPlugin,me.eigenraven.lwjgl3ify.core.Lwjgl3ifyCoremod,org.taumc.celeritas.core.CeleritasLoadingPlugin")
    }

    runs.config('server') {
        enabled = false
    }

    mods {
        remap(configurations.modCompileOnly) {
        }
    }
}

dependencies {
    shadow("org.joml:joml:1.10.5")
    implementation("org.joml:joml:1.10.5")
    implementation("zone.rong:mixinbooter:10.5")
    compileOnly("com.gtnewhorizons.retrofuturabootstrap:RetroFuturaBootstrap:1.0.7") {
        exclude group: 'org.apache.logging.log4j'
    }

    modCompileOnly("maven.modrinth:fluidlogged-api:3.0.6")
}

tasks.named("preRunClient") {
    dependsOn("downgradeClient")
}

LWJGLHelper.convertLwjgl2To3(project)

ProductionJarHelper.configureProcessedResources(project)
ProductionJarHelper.setupLegacyFMLManifest(project)
ProductionJarHelper.createShadowRemapJar(project)

