plugins {
    id 'java-gradle-plugin' // so we can assign and ID to our plugin
}

dependencies {
    implementation("com.google.guava:guava:33.1.0-jre")
    implementation("com.google.code.gson:gson:2.10.1")
    implementation("dev.kikugie:stonecutter:0.5-beta.4")
}

repositories {
    mavenCentral()
    maven { url = "https://maven.kikugie.dev/releases" }
    maven { url = "https://maven.kikugie.dev/snapshots" }
}

gradlePlugin {
    plugins {
        register("celeritas-project-manager") {
            id = "celeritas-project-manager"
            implementationClass = "org.embeddedt.embeddium.gradle.stonecutter.CeleritasProjectManagerPlugin"
        }
    }
}
