# Used when a commit is pushed to the repository
# This makes use of caching for faster builds and uploads the resulting artifacts
name: build-snapshot

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build artifacts
        run: ./gradlew reobfJar
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Embeddium
          path: build/libs
