# Used when a commit is pushed to the repository
# This makes use of caching for faster builds and uploads the resulting artifacts
name: build-snapshot

on:
  push:
    branches:
      - stonecutter

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Initialize caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-snapshot-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('src/main/resources/embeddium.accesswidener') }}-${{ hashFiles('settings.gradle') }}
          restore-keys: |
            ${{ runner.os }}-build-snapshot-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('src/main/resources/embeddium.accesswidener') }}-
      - name: Initialize remapped mod caches
        uses: actions/cache@v4
        with:
          path: |
            .gradle/loom-cache
          key: remapped-mods-${{ hashFiles('build.gradle') }}
      - name: Build jars
        run: ./gradlew chiseledPackage
      - name: Publish jars
        continue-on-error: true
        run: ./gradlew publishPackagesToDiscord
