# Used when a commit is pushed to the repository
# This makes use of caching for faster builds and uploads the resulting artifacts
name: build-snapshot

on:
  push:
    branches:
      - stonecutter

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Initialize caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: unimined-${{ runner.os }}-build-snapshot-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('src/main/resources/embeddium.accesswidener') }}-${{ hashFiles('settings.gradle') }}
          restore-keys: |
            unimined-${{ runner.os }}-build-snapshot-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('src/main/resources/embeddium.accesswidener') }}-
      - name: Build jars
        run: ./gradlew chiseledBuild
      - name: Initialize smoke test caches
        uses: actions/cache@v4
        with:
          path: |
            .gradle/minecraft_prod
          key: smoketest-${{ hashFiles('versions.json') }}
          restore-keys: |
            smoketest-
      - name: Update packages
        run: sudo apt-get update
      - name: Run smoke tests
        uses: coactions/setup-xvfb@v1
        with:
          run: ./gradlew chiseledTestProductionJar --no-daemon
      - name: Publish
        run: ./gradlew chiseledPublish
