
name: Build and Test

on:
  
  push:
    branches:
      - 'stonecutter'
      - 'sarder-refactor'
      
  
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build'
        required: true
        type: choice
        options:
          - stonecutter
          - sarder-refactor
        default: 'stonecutter'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TARGET_BRANCH: ${{ github.event.inputs.branch || github.ref_name }}

    steps:
      - name: Checkout sources from branch (${{ env.TARGET_BRANCH }})
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            17
            21

      - name: Initialize Gradle caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ env.TARGET_BRANCH }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('settings.gradle') }}
          restore-keys: |
            gradle-${{ runner.os }}-${{ env.TARGET_BRANCH }}-

      - name: Initialize Unimined caches
        uses: actions/cache@v4
        with:
          path: |
            modern/versions/**/.gradle/unimined
            forge1710/.gradle/unimined
            forge122/.gradle/unimined
            babric/.gradle/unimined
          key: unimined-v2-${{ runner.os }}-${{ env.TARGET_BRANCH }}-${{ hashFiles('modern/build.gradle') }}-${{ hashFiles('settings.gradle.kts') }}
          restore-keys: |
            unimined-v2-${{ runner.os }}-${{ env.TARGET_BRANCH }}-

      - name: Build all packaged jars for ${{ env.TARGET_BRANCH }}
        run: |
          chmod +x gradlew
          ./gradlew packageJar

      - name: Upload packaged jar for ${{ env.TARGET_BRANCH }}
        uses: actions/upload-artifact@v4
        with:
          name: packaged-mod-${{ env.TARGET_BRANCH }}-${{ github.run_number }}
          path: build/libs/*

      - name: Show checksums
        run: find build/libs -name \*.jar | sort | xargs sha256sum
